# Generated by Django 3.1.5 on 2021-03-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthTrackerApp', '0002_auto_20210308_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='RFID',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
