# Generated by Django 3.1.5 on 2021-03-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthTrackerApp', '0003_patient_rfid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='State',
            field=models.CharField(choices=[('Sleeping', 'Sleeping'), ('Falling', 'Falling'), ('Standing', 'Standing'), ('Sitting', 'Sitting')], default='Sleeping', max_length=200),
        ),
    ]
