# Generated by Django 3.1.5 on 2021-03-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthTrackerApp', '0004_auto_20210309_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='measures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tension_state', models.CharField(max_length=200, null=True)),
                ('tension', models.IntegerField(max_length=200, null=True)),
                ('temp_state', models.CharField(max_length=200, null=True)),
                ('temperature', models.IntegerField(max_length=200, null=True)),
                ('id_patient', models.IntegerField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='RFID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Temperature',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Tension',
            field=models.IntegerField(null=True),
        ),
    ]
