# Generated by Django 3.1.5 on 2021-03-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthTrackerApp', '0005_auto_20210309_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measures',
            name='id_patient',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='measures',
            name='temperature',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='measures',
            name='tension',
            field=models.IntegerField(null=True),
        ),
    ]
