# Generated by Django 3.1.7 on 2021-03-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthTrackerApp', '0009_auto_20210310_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measures',
            name='id_patient',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
