# Generated by Django 3.1.7 on 2021-03-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthTrackerApp', '0010_auto_20210310_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='RFID',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Temperature',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Tension',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
