# Generated by Django 3.1.7 on 2021-03-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthTrackerApp', '0011_auto_20210310_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measures',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
