# Generated by Django 3.1.7 on 2021-03-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthTrackerApp', '0012_auto_20210311_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
